In [1]:
import pandas as pd

df = pd.read_csv("./horas_estudioXcalif.csv")
df.head()

   horas estudio  calif
0              1      2
1              2      3
2              3      5
3              4      4
4              5      5

In [2]:
df["x_2"] = df["horas estudio"] **2
df.head()

   horas estudio  calif  x_2
0              1      2    1
1              2      3    4
2              3      5    9
3              4      4   16
4              5      5   25

In [3]:
#Calculo de xy
df["xy"] = df["horas estudio"] * df["calif"]
df.head()

   horas estudio  calif  x_2  xy
0              1      2    1   2
1              2      3    4   6
2              3      5    9  15
3              4      4   16  16
4              5      5   25  25

In [4]:
n = df["horas estudio"].size
suma_conjunta_xy = df["xy"].sum()
suma_conjunta_x_2 = df["x_2"].sum()
suma_conjunta_x = df["horas estudio"].sum()
suma_conjunta_y = df["calif"].sum()
print(f"""
    n = {n}
    Exy = {suma_conjunta_xy}
    Ex_2 = {suma_conjunta_x_2}
    Ex = {suma_conjunta_x}
    Ey = {suma_conjunta_y}
      """)

    n = 5
    Exy = 64
    Ex_2 = 55
    Ex = 15
    Ey = 19

In [11]:
#Formula para la beta 1
def calculate_beta1(n, Exy, Ex, Ey, Ex_2):
    b_0 = ((n*Exy) - (Ex*Ey))/((n*Ex_2)-(Ex**2))
    return b_0
beta_1 =calculate_beta1(n, suma_conjunta_xy, suma_conjunta_x, suma_conjunta_y, suma_conjunta_x_2)
print("Valor de beta_1: ",beta_1)

#Formula para la beta_0
def calculate_beta0(Ey, b_1, Ex, n):
    b_0 = (Ey-(b_1*Ex))/n
    return b_0
beta_0 = calculate_beta0(suma_conjunta_y, beta_1, suma_conjunta_x, n)
print("valor de beta_0: ", beta_0)

Valor de beta_1:  0.7
valor de beta_0:  1.7

In [12]:
#Calcular prediccion 
y = beta_0 + beta_1 * 6
print("Prediccion: ", y)

Prediccion:  5.8999999999999995