In [ ]:
import pandas as pd

In [4]:
df = pd.read_csv("becas.csv")
df.head()

      nombre  apellido fecha_inscripcion  promedio  beca  colegiatura
0       Luis  Anderson  31/12/2023 23:53      0.42   25%         1271
1    Shannon     Hayes  07/05/2024 08:56      9.91   25%         1386
2    Michael      Hall  10/03/2020 08:35      2.51  100%         1319
3  Mackenzie   Maxwell  25/04/2024 10:17      1.05   50%         1286
4   Victoria     Evans  01/06/2020 20:53      0.88   25%         1600

In [5]:
#validar alumnos con beca de 100 tengan promedio mayor a 9
#excluir alumnos con 100 pero promedio menor a 9
df_excluded_100= df[(df["promedio"]< 9) & (df["beca"] == "100%")]
df_excluded_100.index
df_new = df.copy()

df_new.loc[df_excluded_100.index,"beca"] = "0%"
df_new.loc[df_excluded_100.index,"beca"]

#Se modifica la beca a 100% de los que tienen un promedio mayor a 9 y
df_new.loc[(df["promedio"] > 9) & (df["beca"] != "100%"), "beca"] = "100%"
df_new[(df["promedio"] > 9) & (df["beca"] != "100%")]

           nombre apellido fecha_inscripcion  promedio  beca  colegiatura
1         Shannon    Hayes  07/05/2024 08:56      9.91  100%         1386
19          David   Watson  07/09/2021 14:44      9.27  100%         1532
27         Angela     Ward  28/01/2020 18:22      9.07  100%         1453
46        Rebecca   Farmer  26/07/2019 10:54      9.89  100%         1373
56          Jacob  Lambert  14/11/2022 03:25      9.38  100%         1392
...           ...      ...               ...       ...   ...          ...
1924       Collin    Sharp  26/09/2022 01:04      9.04  100%         1329
1947         Tony    White  12/03/2023 14:44      9.31  100%         1542
1961       Ashley     Ross  25/09/2020 19:21      9.67  100%         1284
1974         Seth     Gray  28/08/2021 22:30      9.17  100%         1454
1990  Christopher  Johnson  26/11/2020 03:16      9.17  100%         1362

[154 rows x 6 columns]

In [6]:
df_new.loc[(df["promedio"] < 9) & (df["promedio"] >8 ), "beca" ] = "75%"
df_new.loc[(df["beca"] == "75%") & (df["promedio"] < 8), "beca"] = "0%"
df_new[(df["promedio"] < 9) & (df["promedio"] >8 )]
df_new

         nombre  apellido fecha_inscripcion  promedio  beca  colegiatura
0          Luis  Anderson  31/12/2023 23:53      0.42   25%         1271
1       Shannon     Hayes  07/05/2024 08:56      9.91  100%         1386
2       Michael      Hall  10/03/2020 08:35      2.51    0%         1319
3     Mackenzie   Maxwell  25/04/2024 10:17      1.05   50%         1286
4      Victoria     Evans  01/06/2020 20:53      0.88   25%         1600
...         ...       ...               ...       ...   ...          ...
1995    Tiffany    Turner  26/09/2021 00:44      5.31   25%         1340
1996     Justin       Ray  29/05/2019 09:44      4.51    0%         1393
1997    Russell     Baker  15/07/2022 06:55      7.93   50%         1363
1998    Michele     Clark  14/11/2023 12:57      3.00    0%         1231
1999    Cynthia   Frazier  20/02/2019 05:05      4.91   25%         1308

[2000 rows x 6 columns]

In [7]:
df_new.loc[(df_new["promedio"] > 7) & (df_new["promedio" ] <8) & (df_new["beca"] != "50%"), "beca"] = "50%"
df_new.loc[(df_new["beca"] == "50%") & (df_new["promedio" ] <= 7) , "beca"] = "0%"
df_new

         nombre  apellido fecha_inscripcion  promedio  beca  colegiatura
0          Luis  Anderson  31/12/2023 23:53      0.42   25%         1271
1       Shannon     Hayes  07/05/2024 08:56      9.91  100%         1386
2       Michael      Hall  10/03/2020 08:35      2.51    0%         1319
3     Mackenzie   Maxwell  25/04/2024 10:17      1.05    0%         1286
4      Victoria     Evans  01/06/2020 20:53      0.88   25%         1600
...         ...       ...               ...       ...   ...          ...
1995    Tiffany    Turner  26/09/2021 00:44      5.31   25%         1340
1996     Justin       Ray  29/05/2019 09:44      4.51    0%         1393
1997    Russell     Baker  15/07/2022 06:55      7.93   50%         1363
1998    Michele     Clark  14/11/2023 12:57      3.00    0%         1231
1999    Cynthia   Frazier  20/02/2019 05:05      4.91   25%         1308

[2000 rows x 6 columns]

In [8]:
df_new.loc[(df_new["promedio"] >= 6) & (df_new["promedio" ] <= 7) & (df_new["beca"] != "25%"), "beca"] = "25%"
df_new.loc[(df_new["beca"] == "25%") & (df_new["promedio" ] <= 6) , "beca"] = "0%"
df_new

         nombre  apellido fecha_inscripcion  promedio  beca  colegiatura
0          Luis  Anderson  31/12/2023 23:53      0.42    0%         1271
1       Shannon     Hayes  07/05/2024 08:56      9.91  100%         1386
2       Michael      Hall  10/03/2020 08:35      2.51    0%         1319
3     Mackenzie   Maxwell  25/04/2024 10:17      1.05    0%         1286
4      Victoria     Evans  01/06/2020 20:53      0.88    0%         1600
...         ...       ...               ...       ...   ...          ...
1995    Tiffany    Turner  26/09/2021 00:44      5.31    0%         1340
1996     Justin       Ray  29/05/2019 09:44      4.51    0%         1393
1997    Russell     Baker  15/07/2022 06:55      7.93   50%         1363
1998    Michele     Clark  14/11/2023 12:57      3.00    0%         1231
1999    Cynthia   Frazier  20/02/2019 05:05      4.91    0%         1308

[2000 rows x 6 columns]

In [9]:
df_new.loc[(df_new["promedio"] < 6) , "beca"] = "0%"
df_new

         nombre  apellido fecha_inscripcion  promedio  beca  colegiatura
0          Luis  Anderson  31/12/2023 23:53      0.42    0%         1271
1       Shannon     Hayes  07/05/2024 08:56      9.91  100%         1386
2       Michael      Hall  10/03/2020 08:35      2.51    0%         1319
3     Mackenzie   Maxwell  25/04/2024 10:17      1.05    0%         1286
4      Victoria     Evans  01/06/2020 20:53      0.88    0%         1600
...         ...       ...               ...       ...   ...          ...
1995    Tiffany    Turner  26/09/2021 00:44      5.31    0%         1340
1996     Justin       Ray  29/05/2019 09:44      4.51    0%         1393
1997    Russell     Baker  15/07/2022 06:55      7.93   50%         1363
1998    Michele     Clark  14/11/2023 12:57      3.00    0%         1231
1999    Cynthia   Frazier  20/02/2019 05:05      4.91    0%         1308

[2000 rows x 6 columns]

In [10]:
df_new.loc[(df_new["colegiatura"] == 1500) , "beca"] = "Transporte"
df_new

         nombre  apellido fecha_inscripcion  promedio  beca  colegiatura
0          Luis  Anderson  31/12/2023 23:53      0.42    0%         1271
1       Shannon     Hayes  07/05/2024 08:56      9.91  100%         1386
2       Michael      Hall  10/03/2020 08:35      2.51    0%         1319
3     Mackenzie   Maxwell  25/04/2024 10:17      1.05    0%         1286
4      Victoria     Evans  01/06/2020 20:53      0.88    0%         1600
...         ...       ...               ...       ...   ...          ...
1995    Tiffany    Turner  26/09/2021 00:44      5.31    0%         1340
1996     Justin       Ray  29/05/2019 09:44      4.51    0%         1393
1997    Russell     Baker  15/07/2022 06:55      7.93   50%         1363
1998    Michele     Clark  14/11/2023 12:57      3.00    0%         1231
1999    Cynthia   Frazier  20/02/2019 05:05      4.91    0%         1308

[2000 rows x 6 columns]

In [11]:
#VALIDAR RESULTADOS
PROMEDIO = df_new["promedio"]
BECA = df_new["beca"]
COLEGIATURA = df_new["colegiatura"]

#No debe haber alumnos con beca del 100% y promedio menor a 9
print("Caso 1")
print(df_new[(PROMEDIO < 9) & (BECA == "100%")])
#No debe haber alumnos con beca del 75% y promedio menor a 8
print("Caso 2")
print(df_new[(PROMEDIO < 8) & (BECA == "75%")])
#No debe haber alumnos con beca del 50% y promedio menor a 7
print("Caso 3")
print(df_new[(PROMEDIO < 7) & (BECA == "50%")])
#No debe haber alumnos con beca del 25% y promedio menor a 6
print("Caso 4")
print(df_new[(PROMEDIO < 6) & (BECA == "25%")])
#No debe haber alumnos con beca si su promedio es menor a 6
print("Caso 5")
print(df_new[(PROMEDIO < 6) & (BECA != "0%")])
#No debe haber alumnos con colegiatura de 1500 y beca diferente a "transportes"
print("Caso 6")
print(df_new[(COLEGIATURA == 1500) & (BECA != "transporte")])

Caso 1
Empty DataFrame
Columns: [nombre, apellido, fecha_inscripcion, promedio, beca, colegiatura]
Index: []
Caso 2
Empty DataFrame
Columns: [nombre, apellido, fecha_inscripcion, promedio, beca, colegiatura]
Index: []
Caso 3
Empty DataFrame
Columns: [nombre, apellido, fecha_inscripcion, promedio, beca, colegiatura]
Index: []
Caso 4
Empty DataFrame
Columns: [nombre, apellido, fecha_inscripcion, promedio, beca, colegiatura]
Index: []
Caso 5
         nombre   apellido fecha_inscripcion  promedio        beca  \
20      Matthew  Rodriguez  21/06/2022 07:36      3.61  Transporte
400       Julia       Wall  27/08/2020 09:20      0.65  Transporte
678        Sara     Jordan  06/06/2021 10:27      2.63  Transporte
1832  Elizabeth      Adams  13/08/2021 18:42      4.05  Transporte

      colegiatura
20           1500
400          1500
678          1500
1832         1500
Caso 6
         nombre   apellido fecha_inscripcion  promedio        beca  \
20      Matthew  Rodriguez  21/06/2022 07:36      3.61  Transporte
400       Julia       Wall  27/08/2020 09:20      0.65  Transporte
678        Sara     Jordan  06/06/2021 10:27      2.63  Transporte
762   Katherine       Odom  05/08/2023 17:09      8.71  Transporte
1350   Jennifer       Paul  27/06/2022 21:02      7.76  Transporte
1492    Michael      Brown  20/03/2023 18:19      6.26  Transporte
1832  Elizabeth      Adams  13/08/2021 18:42      4.05  Transporte

      colegiatura
20           1500
400          1500
678          1500
762          1500
1350         1500
1492         1500
1832         1500

In [13]:
df_new.to_csv("becasCleaned.csv",index=False)